catalog_name: marvelous_dev_ops
schema_name: personality_types

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - age
  - introversion_score
  - sensing_score
  - thinking_score
  - judging_score

cat_features:
  - gender
  - interest
  - education

raw_target: personality

target: target
