catalog_name: marvelous_dev_ops
schema_name: personality_types
pipeline_id: 6a01e18e-f81f-4e67-8a2f-33710bb63fc6

parameters:
  n_estimators: 100
  max_depth: 6

num_features:
  - age
  - introversion_score
  - sensing_score
  - thinking_score
  - judging_score

cat_features:
  - gender
  - interest
  - education

raw_target: personality

target: target
