catalog_name: marvelous_dev_ops
schema_name: personality_types
pipeline_id: 8318441b-5461-4ea5-ba29-26e1f015b54e

parameters:
  n_estimators: 100
  max_depth: 6

num_features:
  - age
  - introversion_score
  - sensing_score
  - thinking_score
  - judging_score

cat_features:
  - gender
  - interest
  - education

raw_target: personality

target: target
